

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: TerraformInstaller@1
      displayName: Terraform installer
      inputs:
        terraformVersion: 'latest'
    
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Shyam_Japnaam'
        backendAzureRmResourceGroupName: 'Shyam_naam_karega_raushan'
        backendAzureRmStorageAccountName: 'shyamjapnaam'
        backendAzureRmContainerName: 'shyamcontainer'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'Shyam_Japnaam'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'Shyam_Japnaam'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        environmentServiceNameAzureRM: 'Shyam_Japnaam'

